import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'

const PromoSection = dynamic(() => import('@/components/feature-components/promoSection'))

export default function Home() {

  return (
    <>
      <Head>
        <title>My Story</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <PromoSection></PromoSection>
      </main>
    </>
  )
}

